@startuml

abstract Bien<<Component, AbstractClass>> {
-liquidez: Real
+<<abstract>>calcularValor(): Real
+valorPrendario(): Real
}
class Automovil<<Leaf, ConcreteClass>> extends Bien {
-modelo: Date
-kilometraje: Integer
-costo0km: Real
+calcularValor(): Real
-aniosAntiguedad(): Integer
}
class Inmueble<<Leaf, ConcreteClass>> extends Bien {
-direccion: String
-superficie: Real
-valorM2: Real
+calcularValor(): Real


}
class Alquiler<<Leaf, ConcreteClass>> extends Bien {
-comienzoContrato: Date
-finContrato: Date
-costoMensual: Real
+calcularValor(): Real
-calcularCostoAlquiler(): Real
}
class PrestamoPrendario<<Composite>> extends Bien {
-liquidez: Real Final
+agregarBien(bien: Bien)
+eliminarBien(bien: Bien)
+calcularValor(): Real
+valorPrendario(): Real
}

PrestamoPrendario o-> Bien : -bienes 0..*
@enduml