@startuml

interface IBien<<Component>> {
+calcularValor(): Real
+coeficienteLiquidez(): Real
}
class Automovil<<Leaf>> implements IBien {
-modelo: Date
-kilometraje: Integer
-costo0km: Real
+calcularValor(): Real
+coeficienteLiquidez(): Real
-aniosAntiguedad(): Integer
}
class Inmueble<<Leaf>> implements IBien {
-direccion: String
-superficie: Real
-valorM2: Real
+calcularValor(): Real
+coeficienteLiquidez(): Real
-calcularValorM2(): Real
}
class Alquiler<<Leaf>> implements IBien {
-comienzoContrato: Date
-finContrato: Date
-costoMensual: Real
+calcularValor(): Real
+coeficienteLiquidez(): Real
-calcularCostoAlquiler(): Real
}
class PrestamoPrendario<<Composite>> implements IBien {

+agregarBien(bien: Bien)
+eliminarBien(bien: Bien)
+calcularValor(): Real
+valorPrendario(): Real
}

PrestamoPrendario o-> IBien : -bienes 0..*
@enduml