@startuml

class Dispositivo <<Context>> {
    +send(data: String): String
    +conectarCon(c: Connection)
    +configurarCRC(c: CalculadorCRC)
}

' --- Patrón Strategy para Conexiones ---
interface Connection <<Strategy>> {
    +sendData(data: String, crc: long): String
    +pict(): String
}

class WifiConn {
    -pict: String
    +sendData(data: String, crc: long): String
    +pict(): String
}

class 4GAdapter <<Adapter>> {
    +sendData(data: String, crc: long): String
    +pict(): String
}

class 4GConnection <<Adaptee>> {
    -symb: String
    +transmit(data: String, crc: int): String
    +symb(): String
}

' --- Patrón Strategy para CRC ---
interface CalculadorCRC <<Strategy>> {
    +crcFor(data: String): long
}

class CRC16_Calculator {
    +crcFor(data: String): long
}

class CRC32_Adapter <<Adapter>> {
    +crcFor(data: String): long
}

class CRC32_Calculator <<Adaptee>> {
    +crcFor(data: String): int
}

' --- Clases de Soporte ---
class Display {
    +showBanner(img: String)
}

class Ringer {
    +ring()
}

' --- Relaciones ---
Connection <|.. WifiConn
Connection <|.. 4GAdapter
4GAdapter --> 4GConnection : -connection4G

CalculadorCRC <|.. CRC16_Calculator
CalculadorCRC <|.. CRC32_Adapter
CRC32_Adapter --> CRC32_Calculator : -calculator32

Dispositivo --> Connection : -connection
Dispositivo --> CalculadorCRC : -crcCalculator
Dispositivo --> Display : -display
Dispositivo --> Ringer : -ringer
@enduml