@startuml
class PNGFilterLauncher<<Context>> {
-inputFile: File
-outputFile: File
+main(args: String[])
processArgs(args: String[])
initializeFilters()
}

abstract Filter <<Strategy>> {
+<<abstract>> filter(image: BufferedImage): BufferedImage
}

class Artifacter <<ConcreteStrategy>> {
-tempFile: File
-compressionQuality: float
+filter(image: BufferedImage): BufferedImage
}
class Dull <<ConcreteStrategy>>{
+filter(image: BufferedImage): BufferedImage
}
class Rainbow <<ConcreteStrategy>> {
+filter(image: BufferedImage): BufferedImage
}
class Repeater <<ConcreteStrategy>> {
+filter(image: BufferedImage): BufferedImage
}
class RGBShifter <<ConcreteStrategy>> {
-<<final>> X_REPEAT: Integer
-<<final>> Y_REPEAT: Integer
+filter(image: BufferedImage): BufferedImage
+shiftValue(original, shiftMagnitude: Integer): Integer
}
class RGBShiftRepeater <<ConcreteStrategy>> {
-<<final>> X_REPEAT: Integer
-<<final>> Y_REPEAT: Integer
+filter(image: BufferedImage): BufferedImage
}

PNGFilterLauncher --> Filter : -activeFilters 1..*
PNGFilterLauncher --> Filter : -filters 1..*
Filter <|-- Artifacter
Filter <|-- Dull
Filter <|-- Rainbow
Filter <|-- Repeater
Filter <|-- RGBShifter
Filter <|-- RGBShiftRepeater
RGBShiftRepeater o--> RGBShifter : uses
@enduml